/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.0.0
 *
 * Project: 'NEUDC2023.Release+Default' 
 * Target:  'Release+Default' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "msp.h"



#endif /* RTE_COMPONENTS_H */
